name: Analyze

on: [push, pull_request]

jobs:
  decomp-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install python libraries
      run: |
        pip install -r tools/requirements.txt

    - name: Run decomplint.py
      run: |
        python3 tools/decomplint/decomplint.py ISLE --module ISLE --warnfail
        python3 tools/decomplint/decomplint.py LEGO1 --module LEGO1 --warnfail
