name: Check order

on: [push, pull_request]

jobs:
  checkorder:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install python libraries
      run: |
        pip install -r tools/requirements.txt

    - name: Run decomplint.py
      run: |
        python3 tools/decomplint/decomplint.py --enforce ISLE --module ISLE
        python3 tools/decomplint/decomplint.py --enforce LEGO1 --module LEGO1
